data_directory: "/Users/tevfik/Sandbox/github/PHD/data/src_data/pdbbind/refined-set/"

datasets:
  train:
    - 1a1e
    - 1a3a
    - 1bbl
  validation:
    - 1b1e
    - 1c2a
  test:
    - 1d3z
    - 1e5j