seed: 42
h5_directory: /Users/tevfik/Sandbox/github/PHD/data/pdbbind/refined-set-only-used-in-codon-tests/box161
total_available: 792
total: 93
train_count: 69
validation_count: 24
selected_cases_sorted:
- 1b57
- 1g85
- 1gyy
- 1h2t
- 1ie9
- 1lrh
- 1m48
- 1qbq
- 1qk3
- 1swg
- 1szd
- 1uj5
- 1wc1
- 1wht
- 1wuq
- 1xd0
- 1xff
- 2aac
- 2fmb
- 2i80
- 2qbu
- 2r58
- 2rcn
- 2v25
- 2w9h
- 2wzf
- 2xpk
- 2yfa
- 2ylc
- 2zx7
- 3acx
- 3arx
- 3bu1
- 3e12
- 3gdt
- 3hcm
- 3i51
- 3ies
- 3k4q
- 3kjd
- 3r88
- 3rlr
- 3sfg
- 3tf6
- 3upv
- 3uw5
- 3v78
- 3w5n
- 3zqe
- 4a7i
- 4do4
- 4duh
- 4ih3
- 4j22
- 4jpy
- 4ou3
- 4rpo
- 4u0w
- 4urz
- 4wkn
- 4ykk
- 5ayt
- 5d2r
- 5d3x
- 5f2u
- 5f8y
- 5fyx
- 5hbn
- 5i1q
- 5jhb
- 5kax
- 5l8y
- 5lso
- 5mek
- 5n84
- 5nwi
- 5ost
- 5ulp
- 5var
- 5vij
- 5xpi
- 6b5q
- 6ckw
- 6cwn
- 6eiz
- 6ej2
- 6eq1
- 6fs1
- 6g9i
- 6gzd
- 6hai
- 6hh3
- 6hsh
train:
- 5ayt
- 1szd
- 3upv
- 1g85
- 5fyx
- 4ykk
- 1xd0
- 2xpk
- 3sfg
- 3bu1
- 3w5n
- 4do4
- 5mek
- 2i80
- 5d2r
- 4urz
- 4wkn
- 5lso
- 6ckw
- 4duh
- 4ih3
- 6g9i
- 5var
- 5f8y
- 3e12
- 1qk3
- 3ies
- 5n84
- 3acx
- 3uw5
- 5ulp
- 5d3x
- 3rlr
- 6hh3
- 4a7i
- 5xpi
- 1wc1
- 3i51
- 2v25
- 3kjd
- 3r88
- 2fmb
- 5hbn
- 4rpo
- 4ou3
- 1qbq
- 3gdt
- 5ost
- 3v78
- 1gyy
- 1xff
- 3k4q
- 5kax
- 2rcn
- 5i1q
- 2w9h
- 1lrh
- 1m48
- 2r58
- 3zqe
- 6ej2
- 1swg
- 6eq1
- 3tf6
- 6hsh
- 2qbu
- 1b57
- 6gzd
- 4u0w
validation:
- 6fs1
- 4j22
- 6eiz
- 2wzf
- 5l8y
- 5vij
- 5f2u
- 2zx7
- 2yfa
- 6cwn
- 6hai
- 1ie9
- 4jpy
- 5nwi
- 1uj5
- 5jhb
- 1wht
- 2aac
- 2ylc
- 3arx
- 3hcm
- 1h2t
- 1wuq
- 6b5q
