#data_directory: "/hps/nobackup/arl/chembl/lorenzo/deep_apbs/destData/refined-set_filter/"
#cache_directory: "/Users/tevfik/Sandbox/github/PHD/data/src_data/pdbbind/refined-set/cache"
name: loss_smooth_2
h5_directory: "/hps/nobackup/arl/chembl/tevfik/deep-apbs-data/pdbbind/refined-set_filter"
training:
  early_stopping_patience: 10
  num_epochs: 200
  batch_size: 4
  learning_rate: 0.0005
  weight_decay: 0.0001
  optimizer: "adam"
  scheduler:
    type: "ReduceLROnPlateau"
    factor: 0.2
    patience: 15
    mode: "min"
  loss:
    type: "BCEDiceLoss"
    alpha: 0.5
    smooth: 2.0
    pos_weight: 10.0
validation:
  batch_size: 8
datasets:
  test:
    - 3s0e
    - 1t7d
    - 4r75
    - 2dw7
    - 2fqt
    - 1dqn
    - 5gja
    - 1fiv
    - 5km9
    - 3fjg
    - 5tuz
    - 5mxf
    - 1sw2
    - 5tcj
    - 5g1z
    - 4gbd
    - 5yz2
    - 4jwk
    - 5vij
    - 1dy4
    - 1m48
    - 4non
    - 4fxp
    - 4aia
    - 4jpy
    - 4d1j
    - 5f0f
    - 1h2k
    - 2jdu
    - 4pb2
    - 1wn6
    - 5ayt
    - 1pgp
    - 6evn
    - 5ey0
    - 3m3c
    - 5vd2
    - 2am4
    - 5d0r
    - 3fur
    - 2jfz
    - 5mn1
    - 1rnt
    - 2v54
    - 4tte
    - 1ctt
    - 2q8h
    - 6hh3
    - 5hjq
    - 3b4p
    - 4jal
    - 5uk8
    - 3sw8
    - 1r9l
    - 5ovp
    - 3aaq
    - 1n4k
    - 3e5a
    - 5ct2
    - 4pft
    - 4kif
    - 6g35
    - 3ta0
    - 3p2e
    - 2vb8
    - 4dkp
    - 3kr4
    - 5fol
    - 4eb8
    - 5oa2
    - 2i80
    - 5hwv
    - 2pqb
    - 5er2
    - 3x00
    - 2vc9
    - 3zll
    - 4pzv
    - 5h1u
    - 3hmp
    - 4o6w
    - 5v79
    - 5g1a
    - 4pf5
    - 5n1z
    - 5wxh
    - 5hcv
    - 1g30
    - 1x8d
    - 5ldp
    - 1ua4
    - 4xu1
    - 4nnr
    - 1o1s
    - 1lnm
    - 3rlr
    - 6exi
    - 4l9i
    - 4hws
    - 1f74
    - 2e2p
    - 5f8y
    - 2epn
    - 2d0k
    - 2w9h
    - 2q89
    - 4da5
    - 2yhw
    - 3h8b
    - 5d6j
    - 4ezx
    - 5x62
    - 3ocz
    - 2vzr
    - 4e67
    - 5vi6
    - 4g0y
    - 5dnu
    - 2gyi
    - 4axd
    - 5tcy
    - 5ewk
    - 3arx
    - 4b73
    - 1tkb
    - 4q19
    - 2wca
    - 4bc5
    - 2x6x
    - 1qaw
    - 3t1a
    - 5uxf
    - 3v2n
    - 5laq
    - 2zx7
    - 6mjf
    - 1o5e
    - 3oy8
    - 4b3b
    - 5yhe
    - 1wc1
    - 5dxt
    - 2pv1
    - 2jjb
    - 4cl6
    - 5sym
    - 2ews
    - 1l83
    - 5ko1
    - 4pqa
    - 3acl
    - 4trc
    - 2q8m
    - 3axz
    - 5kh3
    - 5fsx
    - 3tb6
    - 4h85
    - 1a4r
    - 4ipj
    - 4mo4
    - 5b25
    - 5fnu
    - 4qdk
    - 3ikg
    - 5hbn
    - 4rd6
    - 1oba
    - 1ceb
    - 5ovx
    - 4b8y
    - 5t7s
    - 5e6o
    - 1kyv
    - 2rk8
    - 3wto
    - 5kbe
    - 3o9p
    - 3rm9
    - 4bcn
    - 6ayi
    - 2h21
    - 5ouh
    - 4keq
    - 4gzx
    - 2yfx
    - 5kly
    - 4q3t
    - 2gsu
    - 5wbm
    - 4loo
    - 1wuq
    - 2fxv
    - 4ieh
    - 2wjg
    - 3uj9
    - 2euk
    - 2vmc
    - 4c2v
    - 2vk6
    - 6gzd
    - 3nyd
    - 4qrh
    - 5yas
    - 4ge1
    - 5ei3
    - 6cfc
    - 3w9k
    - 1moq
    - 5hct
    - 4z2b
  train:
    - 5uv2
    - 3d0e
    - 1ajp
    - 6ckw
    - 5f1v
    - 1lgt
    - 4w97
    - 1dud
    - 1o5a
    - 4rpo
    - 3o56
    - 4d4d
    - 4psb
    - 1t4v
    - 2nnd
    - 1w9v
    - 5c2o
    - 4a7i
    - 4je7
    - 3r88
    - 6h5x
    - 1fch
    - 5ih9
    - 1ikt
    - 3eeb
    - 3e3c
    - 4m3p
    - 3pb7
    - 5kat
    - 4c1u
    - 4f6u
    - 2amt
    - 4zt8
    - 1wht
    - 5twj
    - 3iog
    - 1qk3
    - 3alt
    - 1tq4
    - 1mfi
    - 2xde
    - 2we3
    - 2bvd
    - 3ipu
    - 3m6r
    - 5l7h
    - 5wuk
    - 6f9g
    - 2ovv
    - 1bxr
    - 4lps
    - 1olx
    - 3lvw
    - 3o5n
    - 5yft
    - 2h6t
    - 2i3h
    - 4ykk
    - 3ocp
    - 4btk
    - 4ufi
    - 4iid
    - 3cf8
    - 2vpe
    - 6f20
    - 4fl2
    - 4hzm
    - 3ckb
    - 4v24
    - 4mjp
    - 3t6b
    - 2uy3
    - 2p53
    - 5bv3
    - 3sr4
    - 1w96
    - 1q5k
    - 3gdt
    - 5mlj
    - 5upe
    - 4yrd
    - 3uw4
    - 1ydk
    - 4cd4
    - 3v78
    - 2w47
    - 1x38
    - 3h78
    - 2gvv
    - 2wq5
    - 1u1b
    - 5mgj
    - 1b55
    - 3h1x
    - 3cke
    - 4en4
    - 3gbe
    - 3wgg
    - 3m3z
    - 3aqt
    - 6f05
    - 2yz3
    - 1nki
    - 4bps
    - 1kjr
    - 4aq6
    - 1xk9
    - 3ebl
    - 1kdk
    - 2uxi
    - 1h0a
    - 4wkn
    - 4c1y
    - 3hit
    - 5azf
    - 3uzj
    - 2v2v
    - 3q2j
    - 1h6h
    - 4e1k
    - 4cu8
    - 3hp9
    - 4oks
    - 5var
    - 4hym
    - 1upf
    - 4b5w
    - 4ih3
    - 4us3
    - 6std
    - 3o75
    - 3qox
    - 4rlu
    - 4bt3
    - 5mmg
    - 1fao
    - 4agq
    - 2qta
    - 5i8g
    - 3e12
    - 3s6t
    - 2v88
    - 2gss
    - 3rf5
    - 3dx4
    - 2reg
    - 4kzu
    - 1m83
    - 4i7l
    - 3jrs
    - 3w5n
    - 6fhu
    - 4cfl
    - 5t8p
    - 4jkw
    - 2v57
    - 1duv
    - 4kp5
    - 1z4o
    - 3qfy
    - 5vcy
    - 4u70
    - 4k7o
    - 6eq1
    - 2r75
    - 1lkl
    - 3rdo
    - 4aci
    - 3dzt
    - 5e89
    - 5l8y
    - 2ydt
    - 4zyf
    - 4duh
    - 6cvv
    - 6mj7
    - 4bny
    - 4ynl
    - 5o58
    - 2hzy
    - 1uz4
    - 4wov
    - 3f3d
    - 1e3v
    - 5tbm
    - 1jqy
    - 3k4q
    - 5qa8
    - 6hsh
    - 3a9i
    - 5ndf
    - 5c5t
    - 4ymh
    - 4dmw
    - 5gmh
    - 1swg
    - 3dgo
    - 3g19
    - 5n18
    - 3pce
    - 5h8e
    - 2q8z
    - 6gwr
    - 1nja
    - 1r1h
    - 2ptz
    - 1gyy
    - 4zme
    - 4tun
    - 3gr2
    - 2j7b
    - 6ftp
    - 2uyq
    - 4z07
    - 6fhk
    - 4de0
    - 4dv8
    - 5we9
    - 1w5y
    - 5m17
    - 5oku
    - 5gsa
    - 4mhz
    - 3exe
    - 3vdb
    - 4zeb
    - 3q6z
    - 5m28
    - 2v58
    - 1qbq
    - 5ltn
    - 3upv
    - 4lxz
    - 2qpu
    - 4nbn
    - 2wuf
    - 4gid
    - 3ao4
    - 4u0w
    - 5evd
    - 4bks
    - 4up5
    - 1qft
    - 2wr8
    - 1dgm
    - 1nw5
    - 4rlt
    - 3t60
    - 1pz5
    - 2vfk
    - 4der
    - 2oym
    - 5f74
    - 2vnp
    - 1v16
    - 5hwu
    - 3k00
    - 4avh
    - 6cwn
    - 5ahw
    - 2fxu
    - 5gof
    - 5c3p
    - 5mek
    - 2hmu
    - 3f8c
    - 2vhj
    - 3n2v
    - 4b1j
    - 1szd
    - 2r58
    - 5wqc
    - 1qji
    - 5z7b
    - 5mrp
    - 4oct
    - 4wk1
    - 4xoe
    - 2uz9
    - 1ii5
    - 3k37
    - 1o7o
    - 5z7j
    - 4ibb
    - 4aq4
    - 2pql
    - 3kyq
    - 2cht
    - 3hv8
    - 4ncn
    - 1lan
    - 5fhm
    - 4fht
    - 5yj8
    - 1k1y
    - 2o4j
    - 4i9h
    - 4oeu
    - 3p8p
    - 4x3k
    - 6euw
    - 4ad6
    - 4nku
    - 5irr
    - 1phw
    - 5i3a
    - 1pot
    - 5e13
    - 2wzf
    - 4x8o
    - 2clk
    - 4dq2
    - 1alw
    - 5oha
    - 2bfr
    - 2b4l
    - 3vx3
    - 4fai
    - 3ewc
    - 3vjc
    - 3jdw
    - 3uug
    - 1txr
    - 1yfz
    - 2qrl
    - 3vvy
    - 3kgq
    - 5m7u
    - 4rdn
    - 4o2b
    - 1mai
    - 3acx
    - 1i1e
    - 4qij
    - 4ara
    - 4ts1
    - 5kby
    - 2hzl
    - 2vo4
    - 3r1v
    - 1m1b
    - 1k27
    - 1xd0
    - 5f2u
    - 5hi7
    - 2tpi
    - 4e70
    - 2ydw
    - 5vo1
    - 6ht1
    - 1qan
    - 2vw2
    - 4zb6
    - 4u43
    - 5c1m
    - 4yzu
    - 3o7u
    - 5k8s
    - 1dar
    - 4xxh
    - 5m04
    - 3fzy
    - 4j48
    - 2ogy
    - 1ogg
    - 3su3
    - 5yl2
    - 2fqy
    - 4kxn
    - 1ogd
    - 4ish
    - 6edr
    - 3w07
    - 1ws4
    - 3pgl
    - 3qt6
    - 3vhk
    - 4yc0
    - 4y2q
    - 3c39
    - 5i1q
    - 4omj
    - 2aac
    - 5h5f
    - 2xn5
    - 2p4s
    - 3hcm
    - 2xg9
    - 1ec9
    - 1jzs
    - 3l4y
    - 3m8u
    - 1ork
    - 2b7d
    - 5kva
    - 6faa
    - 5dus
    - 1ik4
    - 4zow
    - 4kax
    - 5d3x
    - 2xpk
    - 3q1x
    - 5jzi
    - 3ozr
    - 3juk
    - 3hig
    - 5meh
    - 4oiv
    - 1drv
    - 2oi0
    - 2f2h
    - 2p3i
    - 2xn3
    - 4q93
    - 4km0
    - 2buv
    - 6hlx
    - 1m7y
    - 3d2e
    - 3b7r
    - 3ucj
    - 4b9z
    - 5duw
    - 2qbu
    - 4zcs
    - 3pwk
    - 3po1
    - 1d7i
    - 4b6o
    - 2a8g
    - 4epy
    - 3f37
    - 1wcq
    - 5n99
    - 5ulp
    - 3a1e
    - 4lj8
    - 1erb
    - 6bm5
    - 3iss
    - 4bb9
    - 5ave
    - 3hb4
    - 1xap
    - 3ppm
    - 1uho
    - 3mi2
    - 2qbw
    - 5ovv
    - 6f1j
    - 1u0g
    - 2vpo
    - 2r0h
    - 4zl4
    - 6bhv
    - 5fsc
    - 4p3h
    - 6ezq
    - 4rra
    - 1bq4
    - 6d50
    - 3n1c
    - 6iiu
    - 5jhb
    - 4gah
    - 2xef
    - 2fmb
    - 3i73
    - 3tif
    - 2q7q
    - 3k4d
    - 2hjb
    - 4eu0
    - 3sk2
    - 2v25
    - 1wm1
    - 1pkx
    - 3g3r
    - 4l6t
    - 4zw6
    - 3fzn
    - 4ozj
    - 3u10
    - 4az5
    - 5nwi
    - 4ewn
    - 5lso
    - 3bxh
    - 4w9f
    - 2vyt
    - 1d2e
    - 2qtt
    - 2uyn
    - 5lyn
    - 4mss
    - 2qwb
    - 2e1w
    - 3sm2
    - 2oi2
    - 3aho
    - 3n35
    - 1m5w
    - 3iob
    - 4tmn
    - 5vsj
    - 5ivy
    - 2jkp
    - 3lmk
    - 3v5p
    - 1b57
    - 2x09
    - 4kn0
    - 5n17
    - 2mas
    - 3uw5
    - 5d1r
    - 4cs9
    - 4csd
    - 5btx
    - 2wos
    - 3ga5
    - 4dcs
    - 2rcn
    - 3zq9
    - 4i72
    - 3a5y
    - 2ylc
    - 3c2o
    - 4io7
    - 5kax
    - 5xpi
    - 3zi8
    - 3tzm
    - 3a6t
    - 3tf6
    - 4kzq
    - 4bqs
    - 3iw5
    - 6g9i
    - 3t01
    - 6dak
    - 4ih6
    - 3ery
    - 4qxo
    - 4oak
    - 5b2d
    - 1pvn
    - 5htl
    - 2ihj
    - 4jyc
    - 4j22
    - 4l4v
    - 3ies
    - 4do4
    - 4mre
    - 6g0z
    - 3p3g
    - 3zln
    - 1e2k
    - 5z99
    - 4p5z
    - 4ual
    - 4rqv
    - 3mi3
    - 5g61
    - 2sim
    - 5ito
    - 3f78
    - 4oag
    - 3lp7
    - 2j27
    - 3t0x
    - 3ozj
    - 4umc
    - 3w9r
    - 4bqh
    - 3hww
    - 4muv
    - 1bai
    - 5tef
    - 5tmp
    - 6eux
    - 6gf9
    - 1nfu
    - 1lee
    - 1np0
    - 4lkk
    - 4cc5
    - 2a14
    - 1xk5
    - 4w9p
    - 5ipj
    - 1fzq
    - 5i7y
    - 3tmk
    - 4l4z
    - 5f1r
    - 5gs9
    - 3ccw
    - 4ido
    - 3re4
    - 3sfg
    - 4p6c
    - 1pa9
    - 6g2m
    - 4qnb
    - 2wzs
    - 3ai8
    - 3ip8
    - 8a3h
    - 1lyb
    - 3zi0
    - 2ce9
    - 2xp7
    - 1hlk
    - 4rfr
    - 3rv8
    - 4ksy
    - 6gvz
    - 1u1w
    - 4ocq
    - 3i51
    - 3egt
    - 2w8w
    - 4dsy
    - 5nw7
    - 1yvm
  validation:
    - 2v3d
    - 1gai
    - 1fd0
    - 3bu1
    - 6eiz
    - 3f70
    - 3bex
    - 6b5q
    - 5jhk
    - 1x8j
    - 1vfn
    - 1bhx
    - 5vr8
    - 6bbx
    - 3g0i
    - 2haw
    - 2ccb
    - 4aqh
    - 3fwv
    - 3n9s
    - 3pju
    - 4ou3
    - 6cpw
    - 4ko8
    - 4q9o
    - 3f6g
    - 2yfa
    - 4br3
    - 4pop
    - 2h6b
    - 1g85
    - 1grp
    - 1d9i
    - 6hai
    - 1xh5
    - 1r5y
    - 3cm2
    - 4kow
    - 4tpw
    - 6exs
    - 1uj5
    - 2ra6
    - 5m25
    - 3p7i
    - 5lz4
    - 5fcz
    - 1n4h
    - 4iuo
    - 3iae
    - 5op5
    - 1pfu
    - 2cli
    - 6h1u
    - 2xda
    - 2fzg
    - 4yb5
    - 4ggz
    - 1ssq
    - 5z5f
    - 1p19
    - 6c7q
    - 3zso
    - 1ado
    - 6ej2
    - 2i2c
    - 1ai7
    - 6fnq
    - 3kjd
    - 4nl1
    - 4qge
    - 1cnx
    - 5o2d
    - 1nf8
    - 4u54
    - 6eqv
    - 2e94
    - 3k8c
    - 1ie9
    - 5d2r
    - 2yay
    - 5zo8
    - 3td4
    - 5ngz
    - 1a1e
    - 4g95
    - 4xmr
    - 6fs1
    - 3zqe
    - 3ove
    - 1xow
    - 6hly
    - 2rio
    - 1lah
    - 3ouj
    - 1zhy
    - 1h2t
    - 4luz
    - 3kqr
    - 4qpd
    - 4pg9
    - 3ip6
    - 1ew9
    - 6aqs
    - 5yyf
    - 4w9j
    - 6d2o
    - 3g5k
    - 5xg5
    - 4k0o
    - 2jkh
    - 4urz
    - 1y3n
    - 3b2q
    - 4pcs
    - 2exm
    - 4ew3
    - 6ma4
    - 5n9r
    - 4kyh
    - 3k5x
    - 4y0a
    - 2xyt
    - 4qpl
    - 1ui0
    - 5ehr
    - 4jne
    - 4elf
    - 5bw4
    - 4n7u
    - 5uff
    - 4gq4
    - 3dri
    - 3sio
    - 2q6f
    - 1uvt
    - 2vmf
    - 5el9
    - 5his
    - 4ucc
    - 6eyt
    - 1mfa
    - 4unp
    - 3pgu
    - 1c3x
    - 4oma
    - 4bup
    - 1xff
    - 4zgk
    - 4lhm
    - 3hfb
    - 5l8a
    - 4kwf
    - 2y80
    - 5wp5
    - 4cp5
    - 3jyr
    - 4np9
    - 3r5t
    - 1c86
    - 2bo4
    - 4m6u
    - 3o84
    - 4f1l
    - 1rql
    - 2qtn
    - 4a6s
    - 3c8a
    - 1ydr
    - 1xt8
    - 4ndu
    - 1kc7
    - 4ysl
    - 5wl0
    - 4myd
    - 5hrx
    - 2afw
    - 4cpz
    - 3r24
    - 5jsg
    - 3ebp
    - 5edb
    - 2gl0
    - 5fyx
    - 5n84
    - 5edl
    - 5tpx
    - 1g7q
    - 3qps
    - 3usx
    - 5ewa
    - 2cex
    - 3nik
    - 3d78
    - 5w1e
    - 4kqp
    - 1m0q
    - 2jgs
    - 1lrh
    - 5ost
    - 5mby
    - 6gji
    - 3lzz
    - 4b5d
    - 1drj
    - 5m77
    - 1kuk
    - 5dq8
    - 4sga
    - 2hxm

