seed: 42
h5_directory: /Users/tevfik/Sandbox/github/PHD/data/pdbbind/refined-set_minimal_cache_gridfix_v1/box72
total: 93
train_count: 69
validation_count: 24
selected_cases_sorted:
- 10gs
- 184l
- 185l
- 186l
- 187l
- 188l
- 1a1e
- 1a28
- 1a30
- 1a4k
- 1a4r
- 1a4w
- 1a69
- 1a94
- 1a99
- 1a9m
- 1a9q
- 1aaq
- 1ado
- 1afl
- 1ai4
- 1ai5
- 1ai7
- 1aid
- 1ajn
- 1ajp
- 1ajq
- 1ajv
- 1ajx
- 1atr
- 1avn
- 1azm
- 1b05
- 1b40
- 1b55
- 1b57
- 1b6j
- 1b6k
- 1b6l
- 1b8n
- 1b8o
- 1bcu
- 1bdq
- 1bgq
- 1bm7
- 1bn1
- 1bn3
- 1bn4
- 1bnn
- 1bnq
- 1bnt
- 1bnu
- 1bnv
- 1bnw
- 1bq4
- 1bv7
- 1bv9
- 1bwa
- 1bwb
- 1bzc
- 1bzj
- 1c5x
- 1c70
- 1ceb
- 1cgl
- 1cnw
- 1cnx
- 1cny
- 1cps
- 1d3d
- 1d3p
- 1d4h
- 1d4i
- 1d4j
- 1d4k
- 1d4l
- 1d4p
- 1d4y
- 1d6w
- 1d9i
- 1dif
- 1dl7
- 1dmp
- 1ebw
- 1eby
- 1ebz
- 1ec0
- 1ec1
- 1ec2
- 1ec3
- 1ejn
- 1elr
- 1f0s
train:
- 1c5x
- 1a4r
- 1bm7
- 184l
- 1cnx
- 1bzj
- 1a9m
- 1ajq
- 1bdq
- 1b05
- 1bn4
- 1bnt
- 1d4j
- 1afl
- 1c70
- 1bwb
- 1bzc
- 1d4i
- 1dmp
- 1bnu
- 1bnv
- 1ec2
- 1d6w
- 1cnw
- 1b40
- 1a30
- 1b6k
- 1d4k
- 1avn
- 1bn1
- 1d4y
- 1ceb
- 1bcu
- 1elr
- 1bnq
- 1dif
- 1a69
- 1b6j
- 1aid
- 1b8n
- 1b8o
- 1ado
- 1cny
- 1bv9
- 1bv7
- 1a28
- 1b55
- 1d4p
- 1bn3
- 185l
- 1a9q
- 1b6l
- 1d3p
- 1ai7
- 1cps
- 1ajn
- 188l
- 1a1e
- 1ai5
- 1bnn
- 1ebz
- 1a4k
- 1ec0
- 1bgq
- 1f0s
- 1ai4
- 10gs
- 1ec3
- 1bwa
validation:
- 1ec1
- 1bnw
- 1eby
- 1ajp
- 1d4h
- 1d9i
- 1cgl
- 1atr
- 1ajv
- 1ebw
- 1ejn
- 187l
- 1bq4
- 1d4l
- 1a4w
- 1d3d
- 1a94
- 1aaq
- 1ajx
- 1azm
- 1b57
- 186l
- 1a99
- 1dl7
