name: second_config
data_directory: "/Users/tevfik/Sandbox/github/PHD/data/src_data/pdbbind/refined-set/"
cache_directory: "/Users/tevfik/Sandbox/github/PHD/data/src_data/pdbbind/refined-set/cache"
h5_directory: "/Users/tevfik/Sandbox/DATA/pdbbind-limited/"
training:
  early_stopping_patience: 10
  num_epochs: 200
  batch_size: 4
  learning_rate: 0.0005
  weight_decay: 0.0001
  optimizer: "adam"
  scheduler:
    type: "ReduceLROnPlateau"
    factor: 0.2
    patience: 15
    mode: "min"
  loss:
    type: "BCEDiceLoss"
    alpha: 0.5
    smooth: 1.0
    pos_weight: 10.0
validation:
  batch_size: 8

datasets:
  test:
    - 1a1e
    - 1a28
    - 1a30
    - 1a4k
    - 1a4r
    - 1a4w
    - 1a69
#    - 1a94
#    - 1a99
#    - 1a9m
#    - 1a9q
#    - 1aaq
#    - 1ado
#    - 1afl
#    - 1ai4
  train:
    - 1ai5
    - 1ai7
    - 1aid
    - 1ajn
    - 1ajp
    - 1ajq
    - 1ajv
    - 1ajx
    - 1atr
    - 1avn
    - 1azm
    - 1b05
    - 1b40
    - 1b55
    - 1b57
    - 1b6j
    - 1b6k
    - 1b6l
    - 1b8n
    - 1b8o
    - 1bcu
    - 1bdq
    - 1bgq
    - 1bm7
    - 1bn1
    - 1bn3
    - 1bn4
    - 1bnn
    - 1bnq
    - 1bnt
    - 1bnu
    - 1bnv
    - 1bnw
    - 1bq4
    - 1bv7
    - 1bv9
    - 1bwa
    - 1bwb
    - 1bzc
    - 1bzj
    - 1c5x
    - 1c5y
    - 1c70
    - 1c84
    - 1c88
    - 1ceb
    - 1cgl
    - 1cnw
    - 1cnx
    - 1cny
    - 1cps
    - 1d3d
    - 1d3p
    - 1d4h
    - 1d4i
    - 1d4j
    - 1d4k
    - 1d4l
    - 1d4p
    - 1d4y
    - 1d6w
    - 1d9i
    - 1dar
    - 1df8
    - 1dhi
    - 1dhj
    - 1dif
    - 1dl7
    - 1dmp
    - 1dqn
    - 1drv
    - 1dud
    - 1duv
    - 1dy4
    - 1e2k
    - 1e2l
    - 1e3v
    - 1e4h
    - 1e66
    - 1ebw
    - 1eby
    - 1ebz
    - 1ec0
    - 1ec1
    - 1ec2
    - 1ec3
    - 1ec9
    - 1ecq
    - 1egh
    - 1ejn
    - 1elr
    - 1enu
    - 1erb
    - 1ew9
    - 1ezq
    - 1f0r
    - 1f0s
    - 1f3e
    - 1f4f
    - 1f4g
    - 1f4x
    - 1f5k
    - 1f5l
    - 1fao
    - 1fch
    - 1fjs
    - 1fkw
    - 1flr
  validation:
    - 1fo0
    - 1fpc
    - 1ftm
    - 1fzq
    - 1g1d
    - 1g2k
    - 1g2l
    - 1g35
    - 1g45
    - 1g46
    - 1g48
    - 1g4o
    - 1g52
    - 1g53
    - 1g54
