#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONFIGURABLE_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"

OUTPUT_ROOT="${OUTPUT_ROOT:-/Users/tevfik/Sandbox/github/PHD/runs/work6_apbs_only_clip20_new_architecture_sweep_fold1_250epoch_thr040}"
MODELS="${MODELS:-ResNet3D4LGN,SEResNet3D4LGN,CBAMResNet3D4LGN,TinyConvNeXtUNet3D}"
FOLDS="${FOLDS:-1}"
EPOCHS="${EPOCHS:-250}"
EARLY_STOPPING_PATIENCE="${EARLY_STOPPING_PATIENCE:-0}"
VALIDATION_THRESHOLD="${VALIDATION_THRESHOLD:-0.40}"
BASE_FEATURES="${BASE_FEATURES:-8}"
NUM_WORKERS="${NUM_WORKERS:-0}"
SKIP_COMPLETED="${SKIP_COMPLETED:-1}"
CLEAN_INCOMPLETE="${CLEAN_INCOMPLETE:-1}"
DRY_RUN="${DRY_RUN:-0}"

mkdir -p "$OUTPUT_ROOT"

echo "Work6 new architecture sweep"
echo "Output root: $OUTPUT_ROOT"
echo "Models: $MODELS"
echo "Fold(s): $FOLDS"
echo "Epochs: $EPOCHS"

OUTPUT_ROOT="$OUTPUT_ROOT" \
MODELS="$MODELS" \
FEATURE_SET=apbs_only \
CUTOFF_VARIANTS=apbs_clip20 \
FOLDS="$FOLDS" \
EPOCHS="$EPOCHS" \
EARLY_STOPPING_PATIENCE="$EARLY_STOPPING_PATIENCE" \
VALIDATION_THRESHOLD="$VALIDATION_THRESHOLD" \
BASE_FEATURES="$BASE_FEATURES" \
NUM_WORKERS="$NUM_WORKERS" \
SKIP_COMPLETED="$SKIP_COMPLETED" \
CLEAN_INCOMPLETE="$CLEAN_INCOMPLETE" \
DRY_RUN="$DRY_RUN" \
"$SCRIPT_DIR/run_apbs_only_clip20_model_sweep.sh"
